config/routes.rb
Rails.application.routes.draw do
 # resources :blogs
# resources :blogs
resources :users do 
  resources :blogs
end
  get 'home/index'
  
 # get 'sessions/new'
 ## get 'sessions/destroy'
 # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
   root 'home#index'
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs ,dependent: :destroy
  
  has_secure_password
  validates :email, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  
    helper_method :current_user
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      else
      @current_user = nil
      end
    end
  
 

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
 @user=User.find(params[:user_id])
@blogs= @user.blogs

  end

  def new
    @user =User.find(params[:user_id])
    @blog=Blog.new
end

def create
    @user = User.find(params[:user_id])
  @blog = @user.blogs.new(blog_params)



  respond_to do |format|
    if @blog.save
      format.html { redirect_to user_blogs_path(@user)}# ,notice: "Blog was successfully created." }
      format.json { render :show, status: :created, location: @blog }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
end
end
def update
  @user = User.find(params[:user_id])
  @blog=Blog.find(params[:id])

  respond_to do |format|
    if @blog.update(blog_params)
      format.html { redirect_to user_blogs_path(@user), notice: "User was successfully updated." }
      format.json { render :show, status: :ok, location: @blog }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
  end
end

def destroy

  @user = User.find(params[:user_id])
  @blog=Blog.find(params[:id])

  @blog.destroy

  respond_to do |format|
    format.html { redirect_to user_blogs_path(@user), notice: "blog was successfully destroyed." }
    format.json { head :no_content }
  end
end


def show
   @user =User.find(params[:user_id])
   @blog=@user.blogs.find(params[:id])
end

def edit 
  @user =User.find(params[:user_id])
  @blog=@user.blogs.find(params[:id])

end
private 

def blog_params
  params.require(:blog).permit(:title ,:description )
  
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 # before_action :login_check
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    
    
    

    if user && user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to root_url, notice: "Logged in!"
     else
       flash.now[:alert] = "Email or password is invalid"
       render "new"
     end
   end
   def destroy
     session[:user_id] = nil
     redirect_to root_url, notice: "Logged out!"
   end
   def login_check
   
  
  #if current_user.present?
   #redirect_to root_url
  #end
  
 end

  end
  
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  
  #before_action :login_check ,only: %i[  new create show edit update destroy ]
  



  # GET /users or /users.json
  def index
    @users = User.all
  
   # (not sure if the @blog line is right)
  end
   def vlog
   end
  
  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    #def login_check
     
     
    # if current_user.present?
     # redirect_to root_url
   #  end
     
  #  end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :mobile, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<%# <div id="<%= dom_id blog %>" 
  <p>
    <strong>Title:</strong>
    <%= @blog.title %>
  </p>

  <p>
    <strong>description:</strong>
    <%= @blog.description %>
  </p>
  </br>
  


</div>

app/views/blogs/_form.html.erb
<%= form_with(model: [@user,@blog]) do |form| %>
  
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  
  <!--  <div> 
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div> -->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>editing</h1>

<%= render 'form',blog: @blog%>

app/views/blogs/index.html.erb
<h2>Blogs of <%= link_to @user.name, @user%></h2>


<ul class="blogs">
  <% @blogs.each do |blog| %>
    <li>
    <h3> <%= blog.title  %>: <h3> </br>
    <%= blog.description %> </br>
     

    Posted By
    <%= @user.name %>
    (<%= time_ago_in_words(blog.created_at) %> ago) </br>
     <%= link_to 'Show this Blog',user_blog_path(@user,blog)%> 
     
    </li>
  <% end %>
   <%= link_to " Create new blog", new_user_blog_path(@user)%> 
</ul>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form",blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", new_user_blog_path(:user_id) %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "blog", object:[@user,@blog] %>
<%# <%= @blog.title %> 
<div>
  <%= link_to "Edit this blog", edit_user_blog_path(@user,@blog) %> ||
    <%= link_to "Back to blogs", user_blogs_path%> ||
    <%= link_to "create new blog", new_user_blog_path(@user)%> 
  <%= button_to "Destroy this blog", [@user,@blog], method: :delete %>
</div>

app/views/home/index.html.erb
<% if current_user %>
 Logged in as <%= current_user.name %> from <%= current_user.address %>.
 <%= link_to 'Log Out', logout_path %> </br> </br>
 for vlog  <%= link_to 'see_vlog' ,user_blogs_path(current_user)%>
 create vlog <%= link_to 'create_vlog ',new_user_blog_path(current_user)%>

<% else %>
 <%= link_to 'Sign Up', signup_path %> or
 <%= link_to 'Log In', login_path %></br> </br>
 <%= link_to "Back to blogs", user_blogs_path(:user_id)%>
<% end %>
<p id='notice'><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userlogin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :mobile, style: "display: block" %>
    <%= form.text_field :mobile %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Mobile:</strong>
    <%= user.mobile %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %> </br>
 <%= link_to 'Log In', login_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", home_index_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> ||
  <%= link_to "Back to users", users_path %> ||
   <%= link_to "login", login_path %>
  <%= button_to "Destroy this user", @blog, method: :delete %>
</div>